services:
    front:
        build:
            context: .docker
        container_name: front
        environment:
            SERVICE_NAME: front
            SERVICE_TAGS: quasar
        working_dir: /var/www
        volumes:
            - .:/var/www
        ports:
          - "8080:8080"
          - "9090:9090"
        stdin_open: true
        tty: true
